---
sftp_root: /var/sftp

sftp_users:
  - name: paas_ap
    password: password

# vsftpd listen port for SFTP role (FTPS mode)
vsftpd_sftp_port: 21
vsftpd_sftp_pasv_min_port: 40000
vsftpd_sftp_pasv_max_port: 40100

sshd_sftp_port: 22
