---
dependency:
  name: galaxy
  options:
    requirements-file: ../../../../requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: win2019-jboss
    box: gusztavvargadr/windows-server-2019-standard
    memory: 6144
    cpus: 2
    groups:
      - windows

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    group_vars:
      windows:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_port: 5985
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  config_options:
    defaults:
      interpreter_python: auto_silent

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
