---
# ansible-vault encrypt inventories/prod/group_vars/linux/secret.yml
ansible_password: "VAULT_ENCRYPTED"
ansible_become_password: "VAULT_ENCRYPTED"
paas_ap_password: "VAULT_ENCRYPTED"
mysql_root_password: "VAULT_ENCRYPTED"
mysql_password: "VAULT_ENCRYPTED"
