---
galaxy_info:
  role_name: ftp
  author: tsmc
  description: Install and configure vsftpd for FTP access
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "8"
dependencies:
  - role: common_setup
