---
- name: Converge
  hosts: all
  become: true
  vars:
    paas_ap_password: password
    sftp_users:
      - name: paas_ap
        password: password
  roles:
    - role: common_setup
    - role: sftp
